# Generated by Django 4.2 on 2025-11-29 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VER', 'Visualización'), ('EXPORTAR', 'Exportación')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=200)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-fecha_hora'], name='auditoria_l_fecha_h_0ad7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='auditoria_l_usuario_31f7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modelo', '-fecha_hora'], name='auditoria_l_modelo_3240b9_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', '-fecha_hora'], name='auditoria_l_accion_eef7fc_idx'),
        ),
    ]
