# Generated by Django 5.2.8 on 2025-11-21 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombres y apellidos completos', max_length=150, verbose_name='Nombre completo')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (8 dígitos)', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a'), ('U', 'Unión libre')], max_length=1, verbose_name='Estado civil')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('nombre_tutor', models.CharField(blank=True, max_length=150, verbose_name='Nombre del tutor (si aplica)')),
                ('enfermedades_previas', models.TextField(blank=True, verbose_name='Enfermedades previas')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguíneo')),
                ('tratamientos_previos', models.TextField(blank=True, verbose_name='Tratamientos dentales previos')),
                ('experiencias_dentales', models.TextField(blank=True, verbose_name='Experiencias dentales (miedo, ansiedad, etc.)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
