# Generated by Django 4.2 on 2025-11-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='e0d55ccc5694419894810d5110490a82', max_length=32, unique=True, verbose_name='Token único')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expira_en', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_ficha', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Token de Ficha Médica',
                'verbose_name_plural': 'Tokens de Fichas Médicas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion_completa', models.TextField(verbose_name='Dirección completa')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('tiene_enfermedades', models.BooleanField(default=False, verbose_name='¿Padece alguna enfermedad?')),
                ('enfermedades_detalle', models.TextField(blank=True, verbose_name='Detalle de enfermedades')),
                ('toma_medicamentos', models.BooleanField(default=False, verbose_name='¿Toma medicamentos?')),
                ('medicamentos_detalle', models.TextField(blank=True, verbose_name='Detalle de medicamentos')),
                ('tiene_alergias', models.BooleanField(default=False, verbose_name='¿Tiene alergias?')),
                ('alergias_detalle', models.TextField(blank=True, verbose_name='Detalle de alergias')),
                ('esta_embarazada', models.BooleanField(blank=True, null=True, verbose_name='¿Está embarazada? (solo mujeres)')),
                ('tiene_cirugias_previas', models.BooleanField(default=False, verbose_name='¿Ha tenido cirugías?')),
                ('cirugias_detalle', models.TextField(blank=True, verbose_name='Detalle de cirugías')),
                ('ultima_visita_dentista', models.DateField(blank=True, null=True, verbose_name='Última visita al dentista')),
                ('tiene_tratamientos_previos', models.BooleanField(default=False, verbose_name='¿Ha tenido tratamientos dentales?')),
                ('tratamientos_previos_detalle', models.TextField(blank=True, verbose_name='Detalle de tratamientos previos')),
                ('problemas_dentales_actuales', models.TextField(verbose_name='Problemas dentales actuales')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la consulta')),
                ('acepta_tratamiento_datos', models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos personales')),
                ('acepta_contacto', models.BooleanField(default=False, verbose_name='Acepta ser contactado por WhatsApp/Email')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de completado')),
                ('ip_completado', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP desde donde se completó')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha Médica de Paciente',
                'verbose_name_plural': 'Fichas Médicas de Pacientes',
                'ordering': ['-fecha_completado'],
            },
        ),
    ]
