# Generated by Django 4.2 on 2025-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_tokenfichapaciente_fichamedicapaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenfichapaciente',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='Token único'),
        ),
    ]
