# Generated by Django 5.2.8 on 2025-11-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Endodoncia muela 36, Blanqueamiento, etc.', max_length=200, verbose_name='Nombre del tratamiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total (S/)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización (opcional)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=12, verbose_name='Estado del tratamiento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (S/)')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=15, verbose_name='Método de pago')),
                ('nota', models.TextField(blank=True, verbose_name='Nota (opcional)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tratamientos.tratamiento', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
