# Generated by Django 5.2.8 on 2025-11-21 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del pago'),
        ),
    ]
