# Generated by Django 4.2 on 2025-11-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('tratamientos', '0003_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente', models.IntegerField(help_text='11-85 según notación FDI', verbose_name='Número de Diente (FDI)')),
                ('cara', models.CharField(choices=[('V', 'Vestibular'), ('L', 'Lingual/Palatino'), ('M', 'Mesial'), ('D', 'Distal'), ('O', 'Oclusal/Incisal'), ('C', 'Completo/Diente entero')], max_length=1, verbose_name='Cara del diente')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado/Resina'), ('corona', 'Corona'), ('ausente', 'Ausente'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('sellante', 'Sellante')], default='sano', max_length=20, verbose_name='Estado/Condición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_dientes', to='pacientes.paciente', verbose_name='Paciente')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dientes_afectados', to='tratamientos.tratamiento', verbose_name='Tratamiento Relacionado')),
            ],
            options={
                'verbose_name': 'Estado de Diente',
                'verbose_name_plural': 'Estados de Dientes',
                'unique_together': {('paciente', 'diente', 'cara')},
            },
        ),
    ]
