# Generated by Django 4.2 on 2025-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0004_estadodiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodiente',
            name='estado',
            field=models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado/Resina'), ('corona', 'Corona'), ('ausente', 'Ausente'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('sellante', 'Sellante'), ('bracket', 'Bracket'), ('retenedor', 'Retenedor'), ('aparato', 'Aparato Removible'), ('extraccion_programada', 'Extracción Programada')], default='sano', max_length=25, verbose_name='Estado/Condición'),
        ),
    ]
