# Generated by Django 4.2 on 2025-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0005_alter_estadodiente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodiente',
            name='estado',
            field=models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado/Resina'), ('corona', 'Corona'), ('ausente', 'Ausente'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('sellante', 'Sellante'), ('bracket', 'Bracket'), ('retenedor', 'Retenedor'), ('aparato', 'Aparato Removible'), ('extraccion_programada', 'Extracción Programada'), ('fractura', 'Fractura'), ('implante', 'Implante'), ('puente', 'Puente'), ('protesis_parcial', 'Prótesis Parcial'), ('protesis_total', 'Prótesis Total'), ('en_erupcion', 'Diente en Erupción'), ('retenido', 'Diente Retenido')], default='sano', max_length=25, verbose_name='Estado/Condición'),
        ),
    ]
