# Generated by Django 4.2 on 2025-11-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('tratamientos', '0006_alter_estadodiente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente', models.CharField(max_length=2, verbose_name='Número de Diente (FDI)')),
                ('cara', models.CharField(choices=[('V', 'Vestibular'), ('L', 'Lingual/Palatino'), ('M', 'Mesial'), ('D', 'Distal'), ('O', 'Oclusal/Incisal')], max_length=1, verbose_name='Cara del diente')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado/Resina'), ('corona', 'Corona'), ('ausente', 'Ausente'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('sellante', 'Sellante'), ('bracket', 'Bracket'), ('retenedor', 'Retenedor'), ('aparato', 'Aparato Removible'), ('extraccion_programada', 'Extracción Programada'), ('fractura', 'Fractura'), ('implante', 'Implante'), ('puente', 'Puente'), ('protesis_parcial', 'Prótesis Parcial'), ('protesis_total', 'Prótesis Total'), ('en_erupcion', 'Diente en Erupción'), ('retenido', 'Diente Retenido')], max_length=25, verbose_name='Estado/Condición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_odontograma', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial de Odontograma',
                'verbose_name_plural': 'Historial de Odontogramas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
