# Generated by Django 4.2 on 2025-11-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultorio', models.CharField(default='Consultorio Dental', max_length=200, verbose_name='Nombre del Consultorio')),
                ('titulo_pdf', models.CharField(default='ODONTOGRAMA', max_length=100, verbose_name='Título del PDF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/logos/', verbose_name='Logo del Consultorio')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Consultorio',
                'verbose_name_plural': 'Configuración del Consultorio',
            },
        ),
    ]
