# Generated by Django 5.2.8 on 2025-11-22 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='notas/imagenes/', verbose_name='Imagen adjunta')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción (opcional)')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Imagen de Nota',
                'verbose_name_plural': 'Imágenes de Nota',
            },
        ),
    ]
