# Generated by Django 5.2.8 on 2025-11-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_imagennota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagennota',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='notas/imagenes/', verbose_name='Imagen adjunta'),
        ),
    ]
