# Generated by Django 4.2 on 2025-11-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_imagennota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagennota',
            name='imagen_drive_url',
            field=models.URLField(blank=True, help_text='Pega aquí el link de compartir de Google Drive', null=True, verbose_name='URL de Google Drive'),
        ),
        migrations.AlterField(
            model_name='imagennota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='notas/imagenes/', verbose_name='Imagen adjunta'),
        ),
    ]
