# Generated by Django 4.2 on 2025-12-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_alter_tokenfichapaciente_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ventana_nasal_mas_cerrada', models.CharField(blank=True, choices=[('derecha', 'Derecha'), ('izquierda', 'Izquierda')], max_length=20, null=True)),
                ('ventana_nasal_respira_mejor', models.CharField(blank=True, choices=[('derecha', 'Derecha'), ('izquierda', 'Izquierda')], max_length=20, null=True)),
                ('sellado_labial_reposo', models.BooleanField(default=False, verbose_name='En reposo')),
                ('fascies_adenoidea', models.BooleanField(default=False, verbose_name='Fascies adenoidea (ojeras)')),
                ('labios_cortados', models.BooleanField(default=False, verbose_name='Labios cortados')),
                ('patron_crecimiento', models.CharField(blank=True, choices=[('braqui', 'Braqui'), ('meso', 'Meso'), ('dolico', 'Dólico')], max_length=20, null=True)),
                ('maloclusion', models.CharField(blank=True, choices=[('clase_i', 'Clase I'), ('clase_ii', 'Clase II'), ('clase_iii', 'Clase III')], max_length=20, null=True)),
                ('mordida_cruzada', models.CharField(blank=True, choices=[('anterior', 'Anterior'), ('derecha', 'Derecha'), ('izquierda', 'Izquierda')], max_length=20, null=True)),
                ('mordida_abierta', models.BooleanField(default=False, verbose_name='Mordida abierta')),
                ('sobremordida', models.CharField(blank=True, choices=[('grado_i', 'Grado I'), ('grado_ii', 'Grado II')], max_length=20, null=True)),
                ('amigdalas_grado', models.CharField(blank=True, choices=[('grado_i', 'Grado I'), ('grado_ii', 'Grado II'), ('grado_iii', 'Grado III')], max_length=20, null=True)),
                ('amigdalas_mas_inflamada', models.CharField(blank=True, choices=[('derecha', 'Derecha'), ('izquierda', 'Izquierda')], max_length=20, null=True)),
                ('masticador_derecho', models.BooleanField(default=False, verbose_name='Masticador Derecho')),
                ('masticador_izquierdo', models.BooleanField(default=False, verbose_name='Masticador Izquierdo')),
                ('prefiere_yogurt', models.BooleanField(default=False, verbose_name='Prefiere Yogurt')),
                ('prefiere_manzana', models.BooleanField(default=False, verbose_name='Prefiere Manzana')),
                ('prefiere_naranja', models.BooleanField(default=False, verbose_name='Prefiere Naranja')),
                ('prefiere_zumo', models.BooleanField(default=False, verbose_name='Prefiere Zumo')),
                ('corta_bocados', models.BooleanField(default=False, verbose_name='¿Corta a bocados?')),
                ('tiempo_comer', models.CharField(blank=True, choices=[('menos_20', '< 20 min'), ('30_min', '30 min'), ('mas_30', '> 30 min')], max_length=20, null=True)),
                ('aguanta_5min_labios_sellados', models.BooleanField(default=False, verbose_name='¿Aguanta 5 min con labios sellados?')),
                ('dia_mantiene_sellado', models.BooleanField(default=False, verbose_name='¿Durante el día mantiene el sellado labial?')),
                ('durmiendo_mantiene_sellado', models.BooleanField(default=False, verbose_name='¿Durmiendo mantiene el sellado labial?')),
                ('es_respirador_oral', models.BooleanField(default=False, verbose_name='¿Es respirador oral?')),
                ('deglucion_traga_normalidad', models.BooleanField(default=False, verbose_name='Traga con normalidad')),
                ('deglucion_traga_dificultad', models.BooleanField(default=False, verbose_name='Traga con dificultad')),
                ('deglucion_lengua_dientes', models.BooleanField(default=False, verbose_name='Mete la lengua entre los dientes')),
                ('deglucion_lengua_marcas', models.BooleanField(default=False, verbose_name='Lengua con marcas en los bordes')),
                ('lengua_boca_abierta', models.CharField(blank=True, choices=[('muy_suelta', 'Al sacar la lengua es capaz de alcanzar la nariz: Lengua muy suelta'), ('suelta', 'Con la boca abierta la lengua llega al paladar: Lengua suelta'), ('frenectomia_recomendable', 'Con la boca abierta a lengua se queda a mitad de camino: Frenectomía recomendable'), ('frenectomia_segura', 'Con la boca abierta la lengua apenas sobrepasa los incisivos inferiores: Frenectomía segura')], max_length=50, null=True)),
                ('es_alergico', models.BooleanField(default=False, verbose_name='¿Es alérgico a algo?')),
                ('alergico_a_que', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿A qué?')),
                ('resfrios_ultimo_anio', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('una', 'Una'), ('dos', 'Dos'), ('tres', 'Tres'), ('mas_tres', 'Más de tres')], max_length=20, null=True, verbose_name='Resfríos último año')),
                ('enfermedades_respiratorias', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('una', 'Una'), ('dos', 'Dos'), ('tres', 'Tres'), ('mas_tres', 'Más de tres')], max_length=20, null=True, verbose_name='Amigdalitis/rinitis/otitis/bronquitis')),
                ('antibioticos_ultimo_anio', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('una', 'Una'), ('dos', 'Dos'), ('tres', 'Tres'), ('mas_tres', 'Más de tres')], max_length=20, null=True, verbose_name='Antibióticos último año')),
                ('respiracion_nocturna', models.CharField(blank=True, choices=[('boca_cerrada_sin_ruido', 'Boca cerrada, sin ruido'), ('boca_cerrada_ronca', 'Boca cerrada, ronca'), ('boca_abierta_ronca_babea', 'Boca abierta, ronca y babea')], max_length=50, null=True)),
                ('movilidad_dormir', models.CharField(blank=True, choices=[('tranquilo', 'Tranquilo'), ('agitado', 'Se mueve mucho o agitado')], max_length=20, null=True)),
                ('bruxismo', models.CharField(blank=True, choices=[('centrico', 'Céntrico'), ('excentrico', 'Excéntrico')], max_length=20, null=True)),
                ('recuperacion_despertar', models.CharField(blank=True, choices=[('descansado', 'Se levanta descansado'), ('cuesta', 'Le cuesta levantarse')], max_length=20, null=True)),
                ('eval_masticacion', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mejorable', 'Mejorable'), ('muy_mejorable', 'Muy mejorable')], max_length=20, null=True)),
                ('eval_respiracion', models.CharField(blank=True, choices=[('normal', 'Normal (nasal)'), ('mejorable', 'Mejorable (mixta)'), ('muy_mejorable', 'Muy mejorable (oral)')], max_length=20, null=True)),
                ('eval_deglucion', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mejorable', 'Mejorable'), ('muy_mejorable', 'Muy mejorable')], max_length=20, null=True)),
                ('fonacion', models.CharField(blank=True, choices=[('normal', 'Habla normal'), ('dificultad', 'Dificultad con algunas sílabas')], max_length=20, null=True)),
                ('actividad_fisica', models.CharField(blank=True, choices=[('mucho', 'Mucho ejercicio diario'), ('esporadico', 'Esporádico'), ('no_hace', 'No hace ejercicio')], max_length=20, null=True)),
                ('habitos_alimentarios', models.CharField(blank=True, choices=[('sano', 'Come sano y a sus horas'), ('sano_snacks', 'Come sano + snacks'), ('procesado', 'Come mucho procesado y a deshora')], max_length=20, null=True)),
                ('horas_pantallas', models.CharField(blank=True, choices=[('no_usa', 'No usa'), ('1h', '1h'), ('2h', '2h'), ('3h', '3h')], max_length=10, null=True)),
                ('estado_satisfactorio', models.BooleanField(default=False, verbose_name='Satisfactorio')),
                ('estado_mejorable', models.BooleanField(default=False, verbose_name='Mejorable')),
                ('estado_muy_mejorable', models.BooleanField(default=False, verbose_name='Muy mejorable')),
                ('antecedentes_interes', models.TextField(blank=True, null=True, verbose_name='Antecedentes de interés')),
                ('enfermedad_actual', models.TextField(blank=True, null=True, verbose_name='Enfermedad actual')),
                ('medicacion_actual', models.TextField(blank=True, null=True, verbose_name='Medicación actual')),
                ('plan_refuerzo_habitos', models.BooleanField(default=False, verbose_name='Solo refuerzo de hábitos saludables')),
                ('plan_placa_confort', models.BooleanField(default=False, verbose_name='PlacaConfort y recomendaciones')),
                ('plan_deglu_confort', models.BooleanField(default=False, verbose_name='DegluConfort y recomendaciones')),
                ('plan_nariz_confort', models.BooleanField(default=False, verbose_name='NarizConfort y recomendaciones')),
                ('plan_mascalin', models.BooleanField(default=False, verbose_name='Mascalín (>5 años)')),
                ('plan_retirada_lacteos', models.BooleanField(default=False, verbose_name='Retirada lácteos (1 mes)')),
                ('plan_evitar_azucar', models.BooleanField(default=False, verbose_name='Evitar azúcar y harinas')),
                ('plan_alimentos_duros', models.BooleanField(default=False, verbose_name='Alimentos duros/correosos')),
                ('plan_comer_sin_cubiertos', models.BooleanField(default=False, verbose_name='Comer sin cubiertos')),
                ('plan_comer_lado_preferente', models.CharField(blank=True, choices=[('derecho', 'Derecho'), ('izquierdo', 'Izquierdo')], max_length=20, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_funcional', to='pacientes.paciente')),
            ],
        ),
    ]
