# Generated by Django 5.2.8 on 2025-11-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la entrada')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('evolucion', models.TextField(blank=True, verbose_name='Evolución / Plan de tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_historia', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Entrada de Historia Clínica',
                'verbose_name_plural': 'Entradas de Historia Clínica',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImagenHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historias/imagenes/', verbose_name='Imagen (radiografía, foto, etc.)')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción (opcional)')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='historias.entradahistoria', verbose_name='Entrada de historia')),
            ],
            options={
                'verbose_name': 'Imagen de Historia',
                'verbose_name_plural': 'Imágenes de Historia',
            },
        ),
    ]
