# Generated by Django 5.2.8 on 2025-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenhistoria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='historias/imagenes/', verbose_name='Imagen (radiografía, foto, etc.)'),
        ),
    ]
